# Generated by Django 6.0.1 on 2026-01-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
