# Generated by Django 6.0.1 on 2026-01-07 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_habit_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='streak',
        ),
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='Activity', max_length=50),
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='app.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
