# Generated by Django 6.0.1 on 2026-01-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_habit_streak_habit_color_habit_icon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='completion',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('boolean', 'Yes/No'), ('counter', 'Counter'), ('timer', 'Time Duration')], default='boolean', max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#1F85DE', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='calendar', max_length=50),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.habit')),
            ],
        ),
        migrations.AddField(
            model_name='completion',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory'),
        ),
    ]
