# Generated by Django 6.0.1 on 2026-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_completion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
