# Generated by Django 5.2.10 on 2026-01-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='category',
        ),
    ]
