# Generated by Django 5.2.10 on 2026-01-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_completion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCorrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_coefficient', models.DecimalField(decimal_places=4, max_digits=5)),
                ('sample_size', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('habit1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_habit1', to='app.habit')),
                ('habit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_habit2', to='app.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_correlations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-correlation_coefficient'],
                'indexes': [models.Index(fields=['user', '-correlation_coefficient'], name='app_habitco_user_id_1d2302_idx')],
                'unique_together': {('user', 'habit1', 'habit2')},
            },
        ),
    ]
