# Generated by Django 5.2.10 on 2026-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_habitcorrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, help_text="Optional unit for value habit (e.g., 'km', 'miles', 'hours')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('boolean', 'Yes/No'), ('counter', 'Counter'), ('value', 'Decimal Value'), ('rating', 'Rating')], default='boolean', max_length=10),
        ),
    ]
