# Generated by Django 5.2.10 on 2026-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_habit_unit_alter_habit_habit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcorrelation',
            name='dtw_distance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Dynamic Time Warping distance (detects time-shifted patterns)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='habitcorrelation',
            name='spearman_coefficient',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Spearman rank correlation (handles ordinal data better)', max_digits=5, null=True),
        ),
    ]
