# Generated by Django 5.2.10 on 2026-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_habitcorrelation_dtw_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitcorrelation',
            name='correlation_coefficient',
            field=models.DecimalField(decimal_places=4, help_text='Pearson correlation (linear relationships)', max_digits=5),
        ),
    ]
