# Generated by Django 5.2.10 on 2026-01-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_habit_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
