# Generated by Django 5.2.10 on 2026-01-30 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_id_alter_completion_id_alter_habit_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitcorrelation',
            options={'ordering': ['-max_correlation']},
        ),
        migrations.RemoveIndex(
            model_name='habitcorrelation',
            name='app_habitco_user_id_1d2302_idx',
        ),
        migrations.RemoveField(
            model_name='habitcorrelation',
            name='correlation_coefficient',
        ),
        migrations.AddField(
            model_name='habitcorrelation',
            name='max_correlation',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Maximum correlation strength across all methods (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='habitcorrelation',
            name='pearson_coefficient',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pearson correlation (linear relationships)', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='habitcorrelation',
            index=models.Index(fields=['user', '-max_correlation'], name='app_habitco_user_id_6ec931_idx'),
        ),
    ]
